version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      time: "07:00"
      timezone: Asia/Tokyo
    groups:
      npm-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
      time: "07:00"
      timezone: Asia/Tokyo
    groups:
      cargo-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      time: "07:00"
      timezone: Asia/Tokyo
